title: Gwod's Blog
author: Guo Dejie
email: dejie.guo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thinker, musician and a programmer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
